// Catálogo de referencia: municipios de Venezuela agrupados por estado.
//
// Fuente: ANEXO "Listado de municipios de Venezuela" (Instituto Nacional de
// Estadística). Es dato de referencia estático — igual que `ESTADOS_VENEZUELA`
// en `seed.ts` — por lo que vive en código y no requiere base de datos.
//
// Las claves de `MUNICIPIOS_POR_ESTADO` coinciden EXACTAMENTE con los nombres
// de `ESTADOS_VENEZUELA`. Dos ajustes respecto al PDF de origen:
//   - El PDF lista el estado como "Vargas"; aquí se mapea al nombre vigente
//     "La Guaira" (su único municipio sigue llamándose Vargas).
//   - El PDF rotula el municipio capital de Mérida como "Miranda (Mérida)",
//     lo que duplicaba "Miranda". Se corrige a "Libertador (Mérida)", el
//     nombre real del municipio cuya capital es la ciudad de Mérida.
//
// `nombre` es el municipio (sin el prefijo "Municipio " que el PDF usa de
// forma inconsistente). `capital` es la ciudad/cabecera entre paréntesis del
// PDF; se muestra en el selector para que la persona reconozca la zona, pero
// el valor que se guarda en la solicitud es solo `nombre`.

export type Municipio = {
  nombre: string;
  capital: string;
};

export const MUNICIPIOS_POR_ESTADO: Record<string, Municipio[]> = {
  "Distrito Capital": [{ nombre: "Libertador", capital: "Caracas" }],
  "La Guaira": [{ nombre: "Vargas", capital: "La Guaira" }],
  Carabobo: [
    { nombre: "Bejuma", capital: "Bejuma" },
    { nombre: "Carlos Arvelo", capital: "Güigüe" },
    { nombre: "Diego Ibarra", capital: "Mariara" },
    { nombre: "Guacara", capital: "Guacara" },
    { nombre: "Juan José Mora", capital: "Morón" },
    { nombre: "Libertador", capital: "Tocuyito" },
    { nombre: "Los Guayos", capital: "Los Guayos" },
    { nombre: "Miranda", capital: "Miranda" },
    { nombre: "Montalbán", capital: "Montalbán" },
    { nombre: "Naguanagua", capital: "Naguanagua" },
    { nombre: "Puerto Cabello", capital: "Puerto Cabello" },
    { nombre: "San Diego", capital: "San Diego" },
    { nombre: "San Joaquín", capital: "San Joaquín" },
    { nombre: "Valencia", capital: "Valencia" },
  ],
  Aragua: [
    { nombre: "Bolívar", capital: "San Mateo" },
    { nombre: "Camatagua", capital: "Camatagua" },
    { nombre: "Francisco Linares Alcántara", capital: "Santa Rita" },
    { nombre: "Girardot", capital: "Maracay" },
    { nombre: "José Ángel Lamas", capital: "Santa Cruz" },
    { nombre: "José Félix Ribas", capital: "La Victoria" },
    { nombre: "José Rafael Revenga", capital: "El Consejo" },
    { nombre: "Libertador", capital: "Palo Negro" },
    { nombre: "Mario Briceño Iragorry", capital: "El Limón" },
    { nombre: "Ocumare de la Costa de Oro", capital: "Ocumare de la Costa" },
    { nombre: "San Casimiro", capital: "San Casimiro" },
    { nombre: "San Sebastián", capital: "San Sebastián" },
    { nombre: "Santiago Mariño", capital: "Turmero" },
    { nombre: "Santos Michelena", capital: "Las Tejerías" },
    { nombre: "Sucre", capital: "Cagua" },
    { nombre: "Tovar", capital: "Colonia Tovar" },
    { nombre: "Urdaneta", capital: "Barbacoas" },
    { nombre: "Zamora", capital: "Villa de Cura" },
  ],
  Miranda: [
    { nombre: "Acevedo", capital: "Caucagua" },
    { nombre: "Andrés Bello", capital: "San José de Barlovento" },
    { nombre: "Baruta", capital: "Nuestra Señora del Rosario de Baruta" },
    { nombre: "Brión", capital: "Higuerote" },
    { nombre: "Buroz", capital: "Mamporal" },
    { nombre: "Carrizal", capital: "Carrizal" },
    { nombre: "Chacao", capital: "Chacao" },
    { nombre: "Cristóbal Rojas", capital: "Charallave" },
    { nombre: "El Hatillo", capital: "El Hatillo" },
    { nombre: "Guaicaipuro", capital: "Los Teques" },
    { nombre: "Independencia", capital: "Santa Teresa del Tuy" },
    { nombre: "Lander", capital: "Ocumare del Tuy" },
    { nombre: "Los Salias", capital: "San Antonio de los Altos" },
    { nombre: "Páez", capital: "Río Chico" },
    { nombre: "Paz Castillo", capital: "Santa Lucía" },
    { nombre: "Pedro Gual", capital: "Cúpira" },
    { nombre: "Plaza", capital: "Guarenas" },
    { nombre: "Simón Bolívar", capital: "San Francisco de Yare" },
    { nombre: "Sucre", capital: "Petare" },
    { nombre: "Urdaneta", capital: "Cúa" },
    { nombre: "Zamora", capital: "Guatire" },
  ],
  Zulia: [
    { nombre: "Almirante Padilla", capital: "El Toro" },
    { nombre: "Baralt", capital: "San Timoteo" },
    { nombre: "Cabimas", capital: "Cabimas" },
    { nombre: "Catatumbo", capital: "Encontrados" },
    { nombre: "Colón", capital: "San Carlos del Zulia" },
    { nombre: "Francisco Javier Pulgar", capital: "Pueblo Nuevo / El Chivo" },
    { nombre: "Jesús Enrique Losada", capital: "La Concepción" },
    { nombre: "Jesús María Semprún", capital: "Casigua el Cubo" },
    { nombre: "La Cañada de Urdaneta", capital: "Concepción" },
    { nombre: "Lagunillas", capital: "Ciudad Ojeda" },
    { nombre: "Machiques de Perijá", capital: "Machiques" },
    { nombre: "Mara", capital: "San Rafael del Moján" },
    { nombre: "Maracaibo", capital: "Maracaibo" },
    { nombre: "Miranda", capital: "Los Puertos de Altagracia" },
    { nombre: "Páez", capital: "Sinamaica" },
    { nombre: "Rosario de Perijá", capital: "La Villa del Rosario" },
    { nombre: "San Francisco", capital: "San Francisco" },
    { nombre: "Santa Rita", capital: "Santa Rita" },
    { nombre: "Simón Bolívar", capital: "Tía Juana" },
    { nombre: "Sucre", capital: "Bobures" },
    { nombre: "Valmore Rodríguez", capital: "Bachaquero" },
  ],
  Mérida: [
    { nombre: "Alberto Adriani", capital: "El Vigía" },
    { nombre: "Andrés Bello", capital: "La Azulita" },
    { nombre: "Antonio Pinto Salinas", capital: "Santa Cruz de Mora" },
    { nombre: "Aricagua", capital: "Aricagua" },
    { nombre: "Arzobispo Chacón", capital: "Canagua" },
    { nombre: "Campo Elías", capital: "Ejido" },
    { nombre: "Caracciolo Parra Olmedo", capital: "Tucani" },
    { nombre: "Cardenal Quintero", capital: "Santo Domingo" },
    { nombre: "Guaraque", capital: "Guaraque" },
    { nombre: "Julio César Salas", capital: "Arapuey" },
    { nombre: "Justo Briceño", capital: "Torondoy" },
    { nombre: "Libertador", capital: "Mérida" },
    { nombre: "Miranda", capital: "Timotes" },
    { nombre: "Obispo Ramos de Lora", capital: "Santa Elena de Arenales" },
    { nombre: "Padre Noguera", capital: "Santa María de Caparo" },
    { nombre: "Pueblo Llano", capital: "Pueblo Llano" },
    { nombre: "Rangel", capital: "Mucuchíes" },
    { nombre: "Rivas Dávila", capital: "Bailadores" },
    { nombre: "Santos Marquina", capital: "Tabay" },
    { nombre: "Sucre", capital: "Lagunillas" },
    { nombre: "Tovar", capital: "Tovar" },
    { nombre: "Tulio Febres Cordero", capital: "Nueva Bolivia" },
    { nombre: "Zea", capital: "Zea" },
  ],
  Táchira: [
    { nombre: "Andrés Bello", capital: "Cordero" },
    { nombre: "Antonio Rómulo Costa", capital: "Las Mesas" },
    { nombre: "Ayacucho", capital: "Colón" },
    { nombre: "Bolívar", capital: "San Antonio del Táchira" },
    { nombre: "Cárdenas", capital: "Táriba" },
    { nombre: "Córdoba", capital: "Santa Ana del Táchira" },
    { nombre: "Fernández Feo", capital: "San Rafael del Piñal" },
    { nombre: "Francisco de Miranda", capital: "San José de Bolívar" },
    { nombre: "García de Hevia", capital: "La Fría" },
    { nombre: "Guásimos", capital: "Palmira" },
    { nombre: "Independencia", capital: "Capacho Nuevo" },
    { nombre: "Jáuregui", capital: "La Grita" },
    { nombre: "José María Vargas", capital: "El Cobre" },
    { nombre: "Junín", capital: "Rubio" },
    { nombre: "Libertad", capital: "Capacho Viejo" },
    { nombre: "Libertador", capital: "Abejales" },
    { nombre: "Lobatera", capital: "Lobatera" },
    { nombre: "Michelena", capital: "Michelena" },
    { nombre: "Panamericano", capital: "Coloncito" },
    { nombre: "Pedro María Ureña", capital: "Ureña" },
    { nombre: "Rafael Urdaneta", capital: "Delicias" },
    { nombre: "Samuel Darío Maldonado", capital: "La Tendida" },
    { nombre: "San Cristóbal", capital: "San Cristóbal" },
    { nombre: "San Judas Tadeo", capital: "Umuquena" },
    { nombre: "Seboruco", capital: "Seboruco" },
    { nombre: "Simón Rodríguez", capital: "San Simón" },
    { nombre: "Sucre", capital: "Queniquea" },
    { nombre: "Torbes", capital: "San Josecito" },
    { nombre: "Uribante", capital: "Pregonero" },
  ],
  Trujillo: [
    { nombre: "Andrés Bello", capital: "Santa Isabel" },
    { nombre: "Boconó", capital: "Boconó" },
    { nombre: "Bolívar", capital: "Sabana Grande" },
    { nombre: "Candelaria", capital: "Chejendé" },
    { nombre: "Carache", capital: "Carache" },
    { nombre: "Escuque", capital: "Escuque" },
    { nombre: "José Felipe Márquez Cañizales", capital: "El Paradero" },
    { nombre: "José Vicente Campo Elías", capital: "Campo Elías" },
    { nombre: "La Ceiba", capital: "Santa Apolonia" },
    { nombre: "Miranda", capital: "El Dividive" },
    { nombre: "Monte Carmelo", capital: "Monte Carmelo" },
    { nombre: "Motatán", capital: "Motatán" },
    { nombre: "Pampán", capital: "Pampán" },
    { nombre: "Pampanito", capital: "Pampanito" },
    { nombre: "Rafael Rangel", capital: "Betijoque" },
    { nombre: "San Rafael de Carvajal", capital: "Carvajal" },
    { nombre: "Sucre", capital: "Sabana de Mendoza" },
    { nombre: "Trujillo", capital: "Trujillo" },
    { nombre: "Urdaneta", capital: "La Quebrada" },
    { nombre: "Valera", capital: "Valera" },
  ],
  Lara: [
    { nombre: "Andrés Eloy Blanco", capital: "Sanare" },
    { nombre: "Crespo", capital: "Duaca" },
    { nombre: "Iribarren", capital: "Barquisimeto" },
    { nombre: "Jiménez", capital: "Quíbor" },
    { nombre: "Morán", capital: "El Tocuyo" },
    { nombre: "Palavecino", capital: "Cabudare" },
    { nombre: "Simón Planas", capital: "Sarare" },
    { nombre: "Torres", capital: "Carora" },
    { nombre: "Urdaneta", capital: "Siquisique" },
  ],
  Falcón: [
    { nombre: "Acosta", capital: "San Juan de los Cayos" },
    { nombre: "Bolívar", capital: "San Luis" },
    { nombre: "Buchivacoa", capital: "Capatárida" },
    { nombre: "Cacique Manaure", capital: "Yaracal" },
    { nombre: "Carirubana", capital: "Punto Fijo" },
    { nombre: "Colina", capital: "La Vela de Coro" },
    { nombre: "Dabajuro", capital: "Dabajuro" },
    { nombre: "Democracia", capital: "Pedregal" },
    { nombre: "Falcón", capital: "Pueblo Nuevo" },
    { nombre: "Federación", capital: "Churuguara" },
    { nombre: "Jacura", capital: "Jacura" },
    { nombre: "Los Taques", capital: "Santa Cruz de Los Taques" },
    { nombre: "Mauroa", capital: "Mene de Mauroa" },
    { nombre: "Miranda", capital: "Santa Ana de Coro" },
    { nombre: "Monseñor Iturriza", capital: "Chichiriviche" },
    { nombre: "Palmasola", capital: "Palmasola" },
    { nombre: "Petit", capital: "Cabure" },
    { nombre: "Píritu", capital: "Píritu" },
    { nombre: "San Francisco", capital: "Mirimire" },
    { nombre: "Silva", capital: "Tucacas" },
    { nombre: "Sucre", capital: "La Cruz de Taratara" },
    { nombre: "Tocópero", capital: "Tocópero" },
    { nombre: "Unión", capital: "Santa Cruz de Bucaral" },
    { nombre: "Urumaco", capital: "Urumaco" },
    { nombre: "Zamora", capital: "Puerto Cumarebo" },
  ],
  Yaracuy: [
    { nombre: "Arístides Bastidas", capital: "San Pablo" },
    { nombre: "Bolívar", capital: "Aroa" },
    { nombre: "Bruzual", capital: "Chivacoa" },
    { nombre: "Cocorote", capital: "Cocorote" },
    { nombre: "Independencia", capital: "Independencia" },
    { nombre: "José Antonio Páez", capital: "Sabana de Parra" },
    { nombre: "La Trinidad", capital: "Boraure" },
    { nombre: "Manuel Monge", capital: "Yumare" },
    { nombre: "Nirgua", capital: "Nirgua" },
    { nombre: "Peña", capital: "Yaritagua" },
    { nombre: "San Felipe", capital: "San Felipe" },
    { nombre: "Sucre", capital: "Guama" },
    { nombre: "Urachiche", capital: "Urachiche" },
    { nombre: "Veroes", capital: "Farriar" },
  ],
  Portuguesa: [
    { nombre: "Agua Blanca", capital: "Agua Blanca" },
    { nombre: "Araure", capital: "Araure" },
    { nombre: "Esteller", capital: "Píritu" },
    { nombre: "Guanare", capital: "Guanare" },
    { nombre: "Guanarito", capital: "Guanarito" },
    { nombre: "Monseñor José Vicente de Unda", capital: "Paraíso de Chabasquén" },
    { nombre: "Ospino", capital: "Ospino" },
    { nombre: "Páez", capital: "Acarigua" },
    { nombre: "Papelón", capital: "Papelón" },
    { nombre: "San Genaro de Boconoito", capital: "Boconoito" },
    { nombre: "San Rafael de Onoto", capital: "San Rafael de Onoto" },
    { nombre: "Santa Rosalía", capital: "El Playón" },
    { nombre: "Sucre", capital: "Biscucuy" },
    { nombre: "Turén", capital: "Villa Bruzual" },
  ],
  Barinas: [
    { nombre: "Alberto Arvelo Torrealba", capital: "Sabaneta" },
    { nombre: "Andrés Eloy Blanco", capital: "El Cantón" },
    { nombre: "Antonio José de Sucre", capital: "Socopo" },
    { nombre: "Arismendi", capital: "Arismendi" },
    { nombre: "Barinas", capital: "Barinas" },
    { nombre: "Bolívar", capital: "Barinitas" },
    { nombre: "Cruz Paredes", capital: "Barrancas" },
    { nombre: "Ezequiel Zamora", capital: "Santa Bárbara" },
    { nombre: "Obispos", capital: "Obispos" },
    { nombre: "Pedraza", capital: "Ciudad Bolivia" },
    { nombre: "Rojas", capital: "Libertad" },
    { nombre: "Sosa", capital: "Ciudad de Nutrias" },
  ],
  Apure: [
    { nombre: "Achaguas", capital: "Achaguas" },
    { nombre: "Biruaca", capital: "Biruaca" },
    { nombre: "Muñoz", capital: "Bruzual" },
    { nombre: "Páez", capital: "Guasdualito" },
    { nombre: "Pedro Camejo", capital: "San Juan de Payara" },
    { nombre: "Rómulo Gallegos", capital: "Elorza" },
    { nombre: "San Fernando", capital: "San Fernando de Apure" },
  ],
  Guárico: [
    { nombre: "Camaguán", capital: "Camaguán" },
    { nombre: "Chaguaramas", capital: "Chaguaramas" },
    { nombre: "El Socorro", capital: "El Socorro" },
    { nombre: "Francisco de Miranda", capital: "Calabozo" },
    { nombre: "José Félix Ribas", capital: "Tucupido" },
    { nombre: "José Tadeo Monagas", capital: "Altagracia de Orituco" },
    { nombre: "Juan Germán Roscio", capital: "San Juan de los Morros" },
    { nombre: "Julián Mellado", capital: "El Sombrero" },
    { nombre: "Las Mercedes", capital: "Las Mercedes" },
    { nombre: "Leonardo Infante", capital: "Valle de la Pascua" },
    { nombre: "Ortiz", capital: "Ortiz" },
    { nombre: "Pedro Zaraza", capital: "Zaraza" },
    { nombre: "San Gerónimo de Guayabal", capital: "Guayabal" },
    { nombre: "San José de Guaribe", capital: "San José de Guaribe" },
    { nombre: "Santa María de Ipire", capital: "Santa María de Ipire" },
  ],
  Cojedes: [
    { nombre: "Anzoátegui", capital: "Cojedes" },
    { nombre: "El Pao de San Juan Bautista", capital: "El Pao" },
    { nombre: "Falcón", capital: "Tinaquillo" },
    { nombre: "Girardot", capital: "El Baúl" },
    { nombre: "Lima Blanco", capital: "Macapo" },
    { nombre: "Ricaurte", capital: "Libertad" },
    { nombre: "Rómulo Gallegos", capital: "Las Vegas" },
    { nombre: "San Carlos de Austria", capital: "San Carlos" },
    { nombre: "Tinaco", capital: "Tinaco" },
  ],
  Bolívar: [
    { nombre: "Caroní", capital: "Ciudad Guayana" },
    { nombre: "Cedeño", capital: "Caicara del Orinoco" },
    { nombre: "El Callao", capital: "El Callao" },
    { nombre: "Gran Sabana", capital: "Santa Elena de Uairén" },
    { nombre: "Heres", capital: "Ciudad Bolívar" },
    { nombre: "Padre Pedro Chien", capital: "El Palmar" },
    { nombre: "Piar", capital: "Upata" },
    { nombre: "Raúl Leoni", capital: "Ciudad Piar" },
    { nombre: "Roscio", capital: "Guasipati" },
    { nombre: "Sifontes", capital: "Tumeremo" },
    { nombre: "Sucre", capital: "Maripa" },
  ],
  Amazonas: [
    { nombre: "Alto Orinoco", capital: "La Esmeralda" },
    { nombre: "Atabapo", capital: "San Fernando de Atabapo" },
    { nombre: "Atures", capital: "Puerto Ayacucho" },
    { nombre: "Autana", capital: "Isla Ratón" },
    { nombre: "Manapiare", capital: "San Juan de Manapiare" },
    { nombre: "Maroa", capital: "Maroa" },
    { nombre: "Río Negro", capital: "San Carlos de Río Negro" },
  ],
  "Delta Amacuro": [
    { nombre: "Antonio Díaz", capital: "Curiapo" },
    { nombre: "Casacoima", capital: "Sierra Imataca" },
    { nombre: "Pedernales", capital: "Pedernales" },
    { nombre: "Tucupita", capital: "Tucupita" },
  ],
  Sucre: [
    { nombre: "Andrés Eloy Blanco", capital: "Casanay" },
    { nombre: "Andrés Mata", capital: "San José de Aerocuar" },
    { nombre: "Arismendi", capital: "Río Caribe" },
    { nombre: "Benítez", capital: "El Pilar" },
    { nombre: "Bermúdez", capital: "Carúpano" },
    { nombre: "Bolívar", capital: "Marigüitar" },
    { nombre: "Cajigal", capital: "Yaguaraparo" },
    { nombre: "Cruz Salmerón Acosta", capital: "Araya" },
    { nombre: "Libertador", capital: "Tunapuy" },
    { nombre: "Mariño", capital: "Irapa" },
    { nombre: "Mejía", capital: "San Antonio del Golfo" },
    { nombre: "Montes", capital: "Cumanacoa" },
    { nombre: "Ribero", capital: "Cariaco" },
    { nombre: "Sucre", capital: "Cumaná" },
    { nombre: "Valdez", capital: "Güiria" },
  ],
  "Nueva Esparta": [
    { nombre: "Antolín del Campo", capital: "Plaza Paraguachi" },
    { nombre: "Arismendi", capital: "La Asunción" },
    { nombre: "Díaz", capital: "San Juan Bautista" },
    { nombre: "García", capital: "El Valle del Espíritu Santo" },
    { nombre: "Gómez", capital: "Santa Ana" },
    { nombre: "Maneiro", capital: "Pampatar" },
    { nombre: "Marcano", capital: "Juan Griego" },
    { nombre: "Mariño", capital: "Porlamar" },
    { nombre: "Península de Macanao", capital: "Boca del Río" },
    { nombre: "Tubores", capital: "Punta de Piedras" },
    { nombre: "Villalba", capital: "San Pedro de Coche" },
  ],
  Monagas: [
    { nombre: "Acosta", capital: "San Antonio" },
    { nombre: "Aguasay", capital: "Aguasay" },
    { nombre: "Bolívar", capital: "Caripito" },
    { nombre: "Caripe", capital: "Caripe" },
    { nombre: "Cedeño", capital: "Caicara" },
    { nombre: "Ezequiel Zamora", capital: "Punta de Mata" },
    { nombre: "Libertador", capital: "Temblador" },
    { nombre: "Maturín", capital: "Maturín" },
    { nombre: "Piar", capital: "Aragua de Maturín" },
    { nombre: "Punceres", capital: "Quiriquire" },
    { nombre: "Santa Bárbara", capital: "Santa Bárbara" },
    { nombre: "Sotillo", capital: "Barrancas" },
    { nombre: "Uracoa", capital: "Uracoa" },
  ],
  Anzoátegui: [
    { nombre: "Anaco", capital: "Anaco" },
    { nombre: "Aragua", capital: "Aragua de Barcelona" },
    { nombre: "Diego Bautista Urbaneja", capital: "Lechería" },
    { nombre: "Fernando de Peñalver", capital: "Puerto Píritu" },
    { nombre: "Francisco de Carmen Carvajal", capital: "Valle de Guanape" },
    { nombre: "Francisco de Miranda", capital: "Pariaguán" },
    { nombre: "Guanta", capital: "Guanta" },
    { nombre: "Independencia", capital: "Soledad" },
    { nombre: "José Gregorio Monagas", capital: "Mapire" },
    { nombre: "Juan Antonio Sotillo", capital: "Puerto la Cruz" },
    { nombre: "Juan Manuel Cajigal", capital: "Onoto" },
    { nombre: "Libertad", capital: "San Mateo" },
    { nombre: "Manuel Ezequiel Bruzual", capital: "Clarines" },
    { nombre: "Pedro María Freites", capital: "Cantaura" },
    { nombre: "Píritu", capital: "Píritu" },
    { nombre: "San José de Guanipa", capital: "San José de Guanipa / El Tigrito" },
    { nombre: "San Juan de Capistrano", capital: "Boca de Uchire" },
    { nombre: "Santa Ana", capital: "Santa Ana" },
    { nombre: "Simón Bolívar", capital: "Barcelona" },
    { nombre: "Simón Rodríguez", capital: "El Tigre" },
    { nombre: "Sir Artur McGregor", capital: "El Chaparro" },
  ],
};

// Devuelve los municipios del estado indicado, o un arreglo vacío si el
// estado no tiene catálogo (defensivo: nunca lanza, así el selector puede
// renderizar de forma segura mientras no hay estado elegido).
export function getMunicipios(estado: string): Municipio[] {
  return MUNICIPIOS_POR_ESTADO[estado] ?? [];
}
